#!/usr/bin/env bash

# Name of the private key
key_name="school"

# Number of bits in the key
key_bits=4096

# Passphrase for the private key
passphrase="betty"

# Check if the key file already exists
if [ -f "$key_name" ]; then
  echo "The key file '$key_name' already exists. Please remove it or choose a different name."
  exit 1
fi

# Generate the RSA key pair with the specified key size and passphrase
ssh-keygen -t rsa -b "$key_bits" -f "$key_name" -N "$passphrase"

# Check the exit status of ssh-keygen
if [ $? -eq 0 ]; then
  echo "RSA key pair generated successfully."
else
  echo "Error generating the RSA key pair."
fi
