#!/usr/bin/env bash
# SSH Client Configuration

Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school
      SendEnv LANG LC_*
      HashKnownHosts yes
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials no
